version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: musicapp-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:16
    container_name: musicapp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mussicapp
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: musicapp-app
    depends_on:
      - mongo
      - postgres
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__ConnectionString=mongodb://mongo:27017
      - MongoDb__DatabaseName=MussicAppDb
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=mussicapp;Username=postgres;Password=postgres
    ports:
      - "8080:8080"

volumes:
  mongo-data:
  pg-data:
